quantizer: ema_reset
epochs: 2000
lr: 1e-4
beta: 0.25
warmup_steps: 500
clip_grad_norm: 1.0
code_num: 1024
code_dim: 512
output_emb_width: 512
down_t: 2
stride_t: 2
width: 512
depth: 3
dilation_growth_rate: 3
norm: batch_norm
activation: gelu
nfeats: 491
ckpt: "/root/workspace/HRI_MLLM/output/VQVAE_full_qpos/checkpoints/vqvae_final_v4.pt"

